name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e
            sudo su - root -c '
              export PATH="/root/.nvm/versions/node/v23.5.0/bin:\$PATH"
              cd ${{ secrets.EC2_PATH }}

              echo "Pulling latest code..."
              git reset origin/main --hard
              git pull origin main

              echo "Restarting PM2..."
              pm2 restart dux-agent-ui
            '
          EOF